vich_uploader:
    db_driver: orm
    mappings:
        credit:
            uri_prefix: '/uploads/images/credit'
            upload_destination: '%kernel.project_dir%/public/uploads/images/credit'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true

